In [2]:
#建立list
a = [1, 3, 5, 7, 9]

b = [2, 4, 6, 8 ,10]

result = []
for i in range(5):
    result.append(a[i] + b[i])

result

[3, 7, 11, 15, 19]

In [1]:
import numpy as np

#透過list建立ndArray

a_array = np.array([1, 3, 5, 7, 9])
a_array * 2

b_array = np.array([2, 4, 6, 8 ,10])

a_array + b_array

array([ 3,  7, 11, 15, 19])

In [5]:
#使用python建立5個亂數元素的list
import random

#list comprehension
[random.randint(50,100) for i in range(5)]


[70, 52, 78, 82, 100]

In [9]:
#使用numpy random 建立亂數
import numpy as np
np.random.randint(50,high=100,size=4)

array([99, 96, 53, 60])

In [11]:
np.random.randint(50,high=100,size=(10, 5))

array([[88, 62, 50, 86, 66],
       [60, 99, 62, 58, 76],
       [63, 58, 81, 83, 82],
       [69, 56, 84, 58, 64],
       [89, 97, 87, 85, 65],
       [93, 74, 84, 55, 91],
       [53, 84, 84, 92, 99],
       [88, 94, 83, 77, 68],
       [93, 83, 76, 59, 69],
       [96, 87, 70, 71, 76]])

In [9]:
a= [1, 2]
print(a)

[1, 2]


In [7]:
a= [1, 2]
a

[1, 2]